using System.Collections.Generic;

using LafnyaToolkit.Core.Text;

namespace CppFormatter
{
    /// <summary>
    /// Applies blank-line rules: ensures exactly one blank line around
    /// blocks and declarations (with start/end-of-parent-block
    /// exceptions), collapses excess blank lines, and trims trailing
    /// whitespace. Lines entirely inside a multi-line string or comment
    /// token are preserved verbatim. Split into this primary
    /// orchestrator plus per-rule files under
    /// <c>BlankLineRules/</c> and shared helpers in
    /// <c>BlankLineRules/BlankLineHelpers.cs</c>.
    /// </summary>
    internal sealed partial class BlankLineProcessor
    {
        /// <summary>Shared stateless instance.</summary>
        public static readonly BlankLineProcessor Instance =
            new BlankLineProcessor();

        private BlankLineProcessor()
        {
        }

        /// <summary>
        /// Ensures exactly one blank line above and below blocks/
        /// declarations (with start/end-of-parent-block exceptions).
        /// Lines entirely inside a multi-line string or comment token
        /// are preserved verbatim and never stripped or regenerated by
        /// the blank-line rules.
        /// </summary>
        /// <param name="lines">The line list.</param>
        /// <param name="text">The full source text corresponding to
        /// <paramref name="lines"/>.</param>
        /// <returns>The processed line list.</returns>
        internal List<string> ApplyBlankLineRules(List<string> lines,
            string text)
        {
            var tokens = CppTokenizer.Instance.Tokenize(text);

            bool[] protectedLines =
                CppTokenizer.Instance.ComputeProtectedLines(text, tokens,
                lines.Count);

            var nonBlank = new List<CppNonBlankEntry>(lines.Count);
            bool prevWasBlank = false;
            bool isFirst = true;

            for (int i = 0; i < lines.Count; i++)
            {
                var line = lines[i];

                bool isProtected = i < protectedLines.Length &&
                    protectedLines[i];

                if (line.Trim().Length == 0 && !isProtected)
                {
                    prevWasBlank = true;
                    continue;
                }

                bool hadBlankAbove = !isFirst && prevWasBlank;

                nonBlank.Add(new CppNonBlankEntry(hadBlankAbove, line,
                    isProtected));

                prevWasBlank = false;
                isFirst = false;
            }

            bool[] isContinuation = ComputeContinuationFlags(nonBlank);
            var result = new List<string>(nonBlank.Count);
            bool prevWasDocComment = false;

            for (int i = 0; i < nonBlank.Count; i++)
            {
                string line = nonBlank[i].Line;
                string trimmed = line.Trim();

                bool isFunctionParamListEnd = trimmed.Contains(")") &&
                    trimmed.EndsWith("{") &&
                    !CppLineClassifier.Instance.IsBlockStartLine(trimmed) &&
                    !trimmed.Contains("(");

                BlankLineRuleResult decision = BlankLineMainRules.Dispatch(
                    nonBlank, i, result, isContinuation,
                    prevWasDocComment, isFunctionParamListEnd,
                    out bool wantBlankAbove, out bool wantBlankBelow);

                if (decision == BlankLineRuleResult.Decided && wantBlankAbove)
                {
                    result.Add(string.Empty);
                }

                result.Add(line);

                if (decision == BlankLineRuleResult.Decided && wantBlankBelow)
                {
                    result.Add(string.Empty);
                }

                if (BlankLineHelpers.IsDocCommentLine(trimmed))
                {
                    prevWasDocComment = true;
                }
                else if (trimmed.Length > 0)
                {
                    prevWasDocComment = false;
                }
            }

            return result;
        }

        /// <summary>
        /// Computes per-entry continuation flags: entry <c>i</c> is a
        /// continuation of the previous statement when its leading
        /// indent is at least <see cref="TextUtils.IndentSize"/>
        /// deeper than the previous entry, provided the previous
        /// statement is incomplete (does not end with <c>;</c>,
        /// <c>:</c>, <c>{</c>, or <c>}</c>). A continuation flag also
        /// propagates to subsequent lines at the same indent unless
        /// they end with <c>{</c> or <c>;</c> or are block-start/
        /// block-end lines.
        /// </summary>
        private static bool[] ComputeContinuationFlags(List<CppNonBlankEntry>
            nonBlank)
        {
            bool[] isContinuation = new bool[nonBlank.Count];

            for (int j = 1; j < nonBlank.Count; j++)
            {
                string curTrimmed = nonBlank[j].Line.Trim();
                int curIndent = nonBlank[j].Line.Length - curTrimmed.Length;

                int prevIndent = nonBlank[j - 1].Line.Length - nonBlank[j -
                    1].Line.TrimStart().Length;

                string prevTrimmed = nonBlank[j - 1].Line.Trim();

                if (curIndent >= prevIndent + TextUtils.IndentSize &&
                    !prevTrimmed.EndsWith(";") &&
                    !prevTrimmed.EndsWith(":") &&
                    !prevTrimmed.EndsWith("{") &&
                    !prevTrimmed.EndsWith("}"))
                {
                    isContinuation[j] = true;
                }
                else if (isContinuation[j - 1] && curIndent == prevIndent)
                {
                    if (!curTrimmed.EndsWith("{") &&
                        !curTrimmed.EndsWith(";") &&
                        !CppLineClassifier.Instance.IsBlockStartLine(curTrimmed) &&
                        !CppLineClassifier.Instance.IsBlockEndLine(curTrimmed))
                    {
                        isContinuation[j] = true;
                    }
                }
            }

            return isContinuation;
        }

        /// <summary>
        /// Collapses 3 or more consecutive blank lines into 1. Lines
        /// entirely inside a multi-line string or comment token are
        /// preserved verbatim and never participate in blank-line
        /// collapsing.
        /// </summary>
        /// <param name="lines">The line list.</param>
        /// <param name="text">The full source text corresponding to
        /// <paramref name="lines"/>.</param>
        /// <returns>The processed line list.</returns>
        internal List<string> CollapseBlankLines(List<string> lines,
            string text)
        {
            var tokens = CppTokenizer.Instance.Tokenize(text);

            bool[] protectedLines =
                CppTokenizer.Instance.ComputeProtectedLines(text, tokens,
                lines.Count);

            var result = new List<string>(lines.Count);
            int blankRun = 0;

            for (int i = 0; i < lines.Count; i++)
            {
                if (i < protectedLines.Length && protectedLines[i])
                {
                    result.Add(lines[i]);
                    blankRun = 0;
                    continue;
                }

                if (lines[i].Trim().Length == 0)
                {
                    blankRun++;

                    if (blankRun <= 1)
                    {
                        result.Add(string.Empty);
                    }
                }
                else
                {
                    blankRun = 0;
                    result.Add(lines[i]);
                }
            }

            return result;
        }

        /// <summary>
        /// Trims trailing whitespace from each line. Lines whose last
        /// character lies inside a multi-line string or comment token
        /// are preserved verbatim to avoid damaging raw string
        /// contents.
        /// </summary>
        /// <param name="lines">The line list.</param>
        /// <param name="text">The full source text corresponding to
        /// <paramref name="lines"/>.</param>
        /// <returns>The processed line list.</returns>
        internal List<string> TrimTrailingWhitespace(List<string> lines,
            string text)
        {
            var tokens = CppTokenizer.Instance.Tokenize(text);
            int[] lineStarts = CppTokenizer.Instance.ComputeLineStarts(lines);

            bool[] endsInside =
                CppTokenizer.Instance.ComputeLineEndsInsideToken(text, tokens,
                lineStarts, lines);

            var result = new List<string>(lines.Count);

            for (int i = 0; i < lines.Count; i++)
            {
                if (i < endsInside.Length && endsInside[i])
                {
                    result.Add(lines[i]);
                }
                else
                {
                    result.Add(lines[i].TrimEnd());
                }
            }

            return result;
        }
    }
}
