using System.Collections.Generic;

namespace CppFormatter
{
    /// <summary>
    /// Applies blank-line rules: ensures exactly one blank line around
    /// blocks and declarations (with start/end-of-parent-block exceptions),
    /// collapses excess blank lines, and trims trailing whitespace. Lines
    /// entirely inside a multi-line string or comment token are preserved
    /// verbatim.
    /// </summary>
    internal static class BlankLineProcessor
    {
        /// <summary>
        /// Ensures exactly one blank line above and below blocks/declarations
        /// (with start/end-of-parent-block exceptions). Lines entirely inside a
        /// multi-line string or comment token are preserved verbatim and never
        /// stripped or regenerated by the blank-line rules.
        /// </summary>
        /// <param name="lines">The line list.</param>
        /// <param name="text">The full source text corresponding to
        /// <paramref name="lines"/>.</param>
        /// <returns>The processed line list.</returns>
        internal static List<string> ApplyBlankLineRules(List<string> lines,
            string text)
        {
            var tokens = Tokenizer.Tokenize(text);

            bool[] protectedLines = Tokenizer.ComputeProtectedLines(text,
                tokens, lines.Count);

            var nonBlank = new List<NonBlankEntry>(lines.Count);
            bool prevWasBlank = false;
            bool isFirst = true;

            for (int i = 0; i < lines.Count; i++)
            {
                var line = lines[i];

                bool isProtected = i < protectedLines.Length &&
                    protectedLines[i];

                if (line.Trim().Length == 0 && !isProtected)
                {
                    prevWasBlank = true;
                    continue;
                }

                bool hadBlankAbove = !isFirst && prevWasBlank;

                nonBlank.Add(new NonBlankEntry(hadBlankAbove, line,
                    isProtected));

                prevWasBlank = false;
                isFirst = false;
            }

            var result = new List<string>(nonBlank.Count);

            for (int i = 0; i < nonBlank.Count; i++)
            {
                string line = nonBlank[i].Line;
                string trimmed = line.Trim();
                bool isBlockStart = TextUtils.IsBlockStartLine(trimmed);
                bool wantBlankAbove = false;

                if (result.Count > 0)
                {
                    string prevTrimmed = result[result.Count - 1].Trim();

                    if (isBlockStart && prevTrimmed.Length > 0 && prevTrimmed !=
                        "{" && !TextUtils.EndsWithOpenBrace(prevTrimmed))
                    {
                        wantBlankAbove = true;
                    }

                    if (!wantBlankAbove &&
                        TextUtils.IsBlockEndLine(prevTrimmed) &&
                        trimmed.Length > 0 && trimmed != "}" &&
                        !trimmed.StartsWith("}"))
                    {
                        wantBlankAbove = true;
                    }

                    if (!wantBlankAbove &&
                        TextUtils.IsIncludeDirective(trimmed) &&
                        TextUtils.IsIncludeDirective(prevTrimmed) &&
                        nonBlank[i].HadBlankAbove)
                    {
                        wantBlankAbove = true;
                    }

                    if (!wantBlankAbove && trimmed.StartsWith("///"))
                    {
                        bool prevIsDocComment = prevTrimmed.StartsWith("///");

                        bool prevIsRegularComment =
                            prevTrimmed.StartsWith("//") ||
                            prevTrimmed.StartsWith("/*") ||
                            prevTrimmed.StartsWith("*");

                        bool prevIsBlockOpenBrace = prevTrimmed == "{" ||
                            TextUtils.EndsWithOpenBrace(prevTrimmed);

                        if (prevTrimmed.Length > 0 && !prevIsDocComment &&
                            !prevIsRegularComment && !prevIsBlockOpenBrace)
                        {
                            wantBlankAbove = true;
                        }
                    }

                    // Preserve author-inserted blank lines between adjacent
                    // single-line statements. Only PRESERVES an existing blank
                    // (hadBlankAbove); never adds one. Both current and previous
                    // non-blank lines must be plain single-line statements.

                    if (!wantBlankAbove && nonBlank[i].HadBlankAbove)
                    {
                        bool currentIsPlainStmt = IsPlainSingleLineStatement(
                            trimmed, nonBlank[i].IsProtected);

                        bool prevIsPlainStmt = IsPlainSingleLineStatement(
                            prevTrimmed, nonBlank[i - 1].IsProtected);

                        if (currentIsPlainStmt && prevIsPlainStmt)
                        {
                            wantBlankAbove = true;
                        }
                    }
                }

                if (wantBlankAbove)
                {
                    result.Add(string.Empty);
                }

                result.Add(line);
            }

            return result;
        }

        /// <summary>
        /// Collapses 3 or more consecutive blank lines into 1. Lines entirely
        /// inside a multi-line string or comment token are preserved verbatim
        /// and never participate in blank-line collapsing.
        /// </summary>
        /// <param name="lines">The line list.</param>
        /// <param name="text">The full source text corresponding to
        /// <paramref name="lines"/>.</param>
        /// <returns>The processed line list.</returns>
        internal static List<string> CollapseBlankLines(List<string> lines,
            string text)
        {
            var tokens = Tokenizer.Tokenize(text);

            bool[] protectedLines = Tokenizer.ComputeProtectedLines(text,
                tokens, lines.Count);

            var result = new List<string>(lines.Count);
            int blankRun = 0;

            for (int i = 0; i < lines.Count; i++)
            {
                if (i < protectedLines.Length && protectedLines[i])
                {
                    result.Add(lines[i]);
                    blankRun = 0;
                    continue;
                }

                if (lines[i].Trim().Length == 0)
                {
                    blankRun++;

                    if (blankRun <= 1)
                    {
                        result.Add(string.Empty);
                    }
                }

                else
                {
                    blankRun = 0;
                    result.Add(lines[i]);
                }
            }

            return result;
        }

        /// <summary>
        /// Trims trailing whitespace from each line. Lines whose last character
        /// lies inside a multi-line string or comment token are preserved
        /// verbatim to avoid damaging raw string contents.
        /// </summary>
        /// <param name="lines">The line list.</param>
        /// <param name="text">The full source text corresponding to
        /// <paramref name="lines"/>.</param>
        /// <returns>The processed line list.</returns>
        internal static List<string> TrimTrailingWhitespace(List<string> lines,
            string text)
        {
            var tokens = Tokenizer.Tokenize(text);
            int[] lineStarts = Tokenizer.ComputeLineStarts(lines);

            bool[] endsInside = Tokenizer.ComputeLineEndsInsideToken(text,
                tokens, lineStarts, lines);

            var result = new List<string>(lines.Count);

            for (int i = 0; i < lines.Count; i++)
            {
                if (i < endsInside.Length && endsInside[i])
                {
                    result.Add(lines[i]);
                }

                else
                {
                    result.Add(lines[i].TrimEnd());
                }
            }

            return result;
        }

        /// <summary>
        /// Determines whether the specified trimmed line is a comment line.
        /// </summary>
        /// <param name="trimmed">The trimmed line to inspect.</param>
        /// <returns>true if the line is a line/block-continuation comment;
        /// otherwise, false.</returns>
        private static bool IsCommentLine(string trimmed)
        {
            return trimmed.StartsWith("//") || trimmed.StartsWith("/*") ||
                trimmed.StartsWith("*");
        }

        /// <summary>
        /// Determines whether the specified trimmed line is a plain C++
        /// single-line statement: not protected, ends with ';' (but not a
        /// block start/end), and is not a comment line.
        /// </summary>
        /// <param name="trimmed">The trimmed line to inspect.</param>
        /// <param name="isProtected">Whether the line is protected (inside a
        /// multi-line string or comment token).</param>
        /// <returns>true if the line is a plain single-line statement;
        /// otherwise, false.</returns>
        private static bool IsPlainSingleLineStatement(string trimmed,
            bool isProtected)
        {
            if (isProtected)
            {
                return false;
            }

            if (trimmed.Length == 0 || !trimmed.EndsWith(";"))
            {
                return false;
            }

            if (TextUtils.IsBlockEndLine(trimmed))
            {
                return false;
            }

            if (TextUtils.IsBlockStartLine(trimmed))
            {
                return false;
            }

            if (IsCommentLine(trimmed))
            {
                return false;
            }

            return true;
        }

        /// <summary>
        /// Carries the per-line metadata required by
        /// <see cref="ApplyBlankLineRules"/>: whether a blank line originally
        /// preceded the non-blank line, the line text itself, and whether the
        /// line is protected (inside a multi-line string or comment token).
        /// </summary>
        private struct NonBlankEntry
        {
            public bool HadBlankAbove;
            public string Line;
            public bool IsProtected;

            public NonBlankEntry(bool hadBlankAbove, string line,
                bool isProtected)
            {
                HadBlankAbove = hadBlankAbove;
                Line = line;
                IsProtected = isProtected;
            }
        }
    }
}
